### ISSUE TITLE
Can i use my own images to reconstruct 3d?

### ISSUE THREAD

**Issue by AskingATonOfQuestions** [HanqingWangAI/PSVH-3d-reconstruction#1]
If so, how do i do that. If i try to change photo i get this message: 

Traceback (most recent call last):
  File "run_case.py", line 453, in <module>
    examples('real')
  File "run_case.py", line 443, in examples
    img = img.reshape([1, img_h, img_w, 3])
ValueError: cannot reshape array of size 65536 into shape (1,128,128,3)

**Comment by HanqingWangAI** [comment]
I believe you should first crop or resize your image to 128*128 resolution and ensure that the image has RGB channels.

**Comment by AskingATonOfQuestions** [comment]
@qweas120 Ok, so i tried, cropping it to 138*138 (original chair images are 138*138). Did not work. Then i tried as you said 128*128. still not work. I use GIMP software. After all i tried taking chair picture and change nothing, but saved and its not working. I dont really understand whats the issue, but im pretty sure it's something with image format. What software and properties did you use for chair photos?

**Comment by HanqingWangAI** [comment]
I guess your image format is PNG? PNG format often has an additional alpha channel which makes the numpy array cannot be reshaped to [1,128,128,3]. 
You may check the shape of the numpy array by inserting `print(img.shape)` before line 443.
