### ISSUE TITLE
How to use other pictures to reconstruct?

### ISSUE THREAD

**Issue by maomaolemon** [HanqingWangAI/PSVH-3d-reconstruction#2]
Sorry to disturb you!
I put a new chair picture in the folder [real_data]. It is .png and 138*138. But it also can’t work.
I want to know whether there are other steps that I should to do, such as modifying the .py file?
Thank you!

**Comment by HanqingWangAI** [comment]
@maomaolemon Does the "can't work" mean bad result or runtime error? If it is a runtime error, could you paste the traceback so I can locate the problem?

**Comment by maomaolemon** [comment]
I use print(img.shape) , and the result is (128, 128, 4).
The error is as follows:

Traceback (most recent call last):
  File "run_case.py", line 454, in <module>
    examples('real')
  File "run_case.py", line 444, in examples
    img = img.reshape([1, img_h, img_w, 3])
ValueError: cannot reshape array of size 65536 into shape (1,128,128,3)

**Comment by maomaolemon** [comment]
I’m glad that I have solved the problem above. I used PS to modify bit depth.
And I have another question: Can I reconstruct other class, like airplane? I have create the real_data and syn_data for airplane. And then I modify the row348 of run_case.py. But when I run the program, the result is also the old result of chair. Is there other steps need to do?
Looking forward to your reply and thanks a lot!

**Comment by HanqingWangAI** [comment]
@maomaolemon You may change [run_case.py Line 348](https://github.com/qweas120/PSVH-3d-reconstruction/blob/master/run_case.py#L348) to `cates = ['02691156']` for aero reconstruction.

**Comment by maomaolemon** [comment]
That’s great! I made several changes to the code and successfully rebuilt the various types. 
Now I have other questions. The main thing in your paper is the construction of two networks, but I don't see that in the code. And I also want to know if there are steps in the code to calculate the IOU?
Thanks a lot!

**Comment by HanqingWangAI** [comment]
@maomaolemon Actually we demonstrate the result of reconstruction before and after the coarse shape refinement (See [Line449-450](https://github.com/qweas120/PSVH-3d-reconstruction/blob/master/run_case.py#L449)). The code for quantitative evaluation is not prepared for now.
